### ISSUE TITLE
vNext support

### ISSUE THREAD

**Issue by roly445** [bitrvmpd/wuffSonic#1]
First of all, great little library.

Just a quick question are you planning to support vNext as I'm running my music server on a nix pc?

Cheers

**Comment by bitrvmpd** [comment]
Thanks for the feedback!, and yes i'm planning to support vNext. I'm going to close this issue when I finish that feature.

**Comment by bitrvmpd** [comment]
Can you try adding the lib using the project.json file on your vNext project ? 

Add this to the dependencies object:
"wuffSonic": "1.0.3-alpha2" 

```
(...)
  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "wuffSonic": "1.0.3-alpha2" 
  },
(...)
```

It's on nuget as [wuffSonic](http://nuget.org/packages/wuffSonic/)
